name: Docker Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: 47.94.200.20
          username: root
          password: Lyj123456..
          script: |
            cd /root
            
            # 卸载所有代理（关键！）
            git config --global --unset http.proxy
            git config --global --unset https.proxy
            
            # 下载代码
            rm -rf firestone
            git clone https://github.com/Dylanly1/firestone.git
            cd firestone
            
            # 重启docker（确保镜像源生效）
            systemctl restart docker
            
            # 停止旧容器
            docker stop myapp || true
            docker rm myapp || true
            
            # 构建
            docker build -t myapp .
            
            # 启动
            docker run -d \
              --name myapp \
              --restart always \
              -p 80:80 \
              myapp
