name: 企业级Docker自动部署

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 连接服务器并自动部署
        uses: appleboy/ssh-action@master
        with:
          host: 47.94.200.20
          username: root
          password: Lyj123456..
          script: |
            cd /root

            # 配置Git加速（解决阿里云拉取GitHub超时）
            git config --global http.https://github.com.proxy http://10.10.10.10:1080
            git config --global https.https://github.com.proxy http://10.10.10.10:1080
            git config --global url."https://".insteadOf git://

            # 下载代码
            rm -rf firestone
            git clone https://github.com/Dylanly1/firestone.git
            cd firestone

            # 停止旧服务
            docker stop myapp || true
            docker rm myapp || true

            # 构建镜像
            docker build -t myapp .

            # 启动容器
            docker run -d \
              --name myapp \
              --restart always \
              --net=host \
              myapp
