name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 47.94.200.20
          username: root
          password: Lyj123456..
          script: |
            cd /root
            git clone https://github.com/hswuz/firestone.git
            cd firestone
            nohup go run main.go > app.log 2>&1 &
